//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parik_PM_AkEntities : DbContext
    {
        public parik_PM_AkEntities()
            : base("name=parik_PM_AkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Price_list> Price_list { get; set; }
        public virtual DbSet<Rabotnik> Rabotnik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yslygi1> Yslygi1 { get; set; }
        public virtual DbSet<zal> zal { get; set; }
        public virtual DbSet<Zapis_> Zapis_ { get; set; }
        public virtual DbSet<Doljnost> Doljnost { get; set; }
    }
}
